---
name: eliud_pkg_chat_model
description: eliud_pkg_chat_model is the model package for eliud_pkg_chat. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_chat
version: 1.0.0
environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  eliud_core_main:                                                                                   # ANDROID IOS             WEB
    path: ../eliud_core_main

  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator:
    path: ../eliud_generator
  lints: ^3.0.0
flutter:
  uses-material-design: true
platforms:
  android: null
  ios: null
  web: null
