---
name: eliud_pkg_chat_model
description: eliud_pkg_chat_model is the model package for eliud_pkg_chat. More info at https://eliud.io
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_chat
version: 1.0.0
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.12.2
  collection: ^1.17.2
  eliud_core:
    path: ../eliud_core
  eliud_core_model:
    path: ../eliud_core_model
  eliud_core_main:
    path: ../eliud_core_main
  eliud_core_helpers:
    path: ../eliud_core_helpers
  eliud_pkg_follow: 
    path: ../eliud_pkg_follow
  eliud_pkg_follow_model: 
    path: ../eliud_pkg_follow_model
  eliud_pkg_medium: 
    path: ../eliud_pkg_medium
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  meta: ^1.9.1
  transparent_image: ^2.0.1
  tuple: ^2.0.2
  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator:
    path: ../eliud_generator
  lints: ^3.0.0
flutter:
  uses-material-design: true
platforms:
  android: null
  ios: null
  web: null
